variable "project_name" {}
variable "region" {}
variable "vpc_cidr" {}
variable "igw" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_subnet-az1_cidr" {}
variable "private_subnet-az2_cidr" {}
variable "public_subnet_az1_id" {}
variable "public_subnet_az2_id" {}
variable "private_subnet-az1_id" {}
variable "private_subnet-az2_id" {}